### ISSUE TITLE
协议维度的疑惑  

### ISSUE THREAD

**Issue by luojiyin1987** [kaiyuanshe/Open-Source-License-filter#1]
[文档](https://kaiyuanshe.feishu.cn/wiki/wikcnRn5pkE3BSvqFUMkJPymaG3)

[原网页地址](https://kaiyuanshe.cn/license-tool/)

  1. 流行程度 Popularity  对应原来的  流行并广泛使用  ？
  2. 复用条件 Reuse Condition   对应什么？
  3. 传染强度 Infection Intensity   对应什么？
  4. 传染范围 Infection Range      对应什么？
  5. 法律管辖 Jurisdiction           对应 司法管辖区 ？
  6. 专利声明 Patent Statement  对应  专利报复条款 还是 授予专利权 ？
  7. 专利报复 Patent Retaliation  对应  专利报复条款 ？
  8. 增强署名 Enhanced Attribution  对应   授予专利权  ？
  9. 隐私漏洞 Privacy Loophole       对应   解决“隐私漏洞 ？
  10. 营销背书 Marketing Endorsement  对应   指定“不推广”功能 ？ 

@TechQuery  ?

**Comment by TechQuery** [comment]
这十个维度的顺序就是步骤向导界面上的问题顺序，我是依照[英文原版](http://oss-watch.ac.uk/apps/licdiff/)来梳理的，中英文的顺序是一样的。

**Comment by luojiyin1987** [comment]
> [文档](https://kaiyuanshe.feishu.cn/wiki/wikcnRn5pkE3BSvqFUMkJPymaG3)
> 
> [原网页地址](https://kaiyuanshe.cn/license-tool/)
> 
> 1. 流行程度 Popularity  对应原来的  流行并广泛使用  ？
> 2. 复用条件 Reuse Condition   对应什么？
> 3. 传染强度 Infection Intensity   对应什么？
> 4. 传染范围 Infection Range      对应什么？
> 5. 法律管辖 Jurisdiction           对应 司法管辖区 ？
> 6. 专利声明 Patent Statement  对应  专利报复条款 还是 授予专利权 ？
> 7. 专利报复 Patent Retaliation  对应  专利报复条款 ？
> 8. 增强署名 Enhanced Attribution  对应   授予专利权  ？
> 9. 隐私漏洞 Privacy Loophole       对应   解决“隐私漏洞 ？
> 10. 营销背书 Marketing Endorsement  对应   指定“不推广”功能 ？
> 
> @TechQuery ?

  1. 流行程度 Popularity  对应            流行并广泛使用
  2. 复用条件 Reuse Condition 对应   重复使用设置许可条件
  3.  传染强度 Infection Intensity 对应  强 弱著作权 
  4.  传染范围 Infection Range     对应   选择  module   File  Libray  level  (当 4 选择 弱著作权时)
  5. 法律管辖 Jurisdiction 对应 司法管辖区 
  6.  专利声明 Patent Statement 对应     授予专利权 
  7.  专利报复 Patent Retaliation 对应     专利报复条款 （ 在6中 选择  我不在乎，我想自己并不拥有专利  或者   我想使用明确授予专利权的许可协议   时会出现 ）
  8.  增强署名 Enhanced Attribution  对应   增强型归属 
  9.   隐私漏洞 Privacy Loophole 对应 解决“隐私漏洞
  10.  营销背书 Marketing Endorsement    是否允许推广
  
疑问  
1 在选择 传染强度 强时 ， 传染范围应该时全部？  
2  在选择  专利声明时 如果是不在乎， 就不应该出现 专利报复 ？
3  在选择  专利声明时  如果是 明确授予专利权的许可协议 ， 才应该有 专利报复？

@TechQuery      还是希望有人了解相关法律原则

**Comment by TechQuery** [comment]
上述纬度对应是对的。

有前后关联的纬度可以在界面控制题目显隐，算法上不传就不纳入计算，对总分的相对高低没有影响。

**Comment by luojiyin1987** [comment]
隐私漏洞 Privacy Loophole  是指开发者对开源代码进行二次开发后， 需要对代码进行维护 ？  @TechQuery

**Comment by luojiyin1987** [comment]
我做了一个设置 ，当传染强度 Infection Intensity 为强时 ，传染范围 Infection Range 到 File，  原来的 matrix.json 文件 是没相关值得。

**Comment by TechQuery** [comment]
> 隐私漏洞 Privacy Loophole 是指开发者对开源代码进行二次开发后， 需要对代码进行维护 ？ @TechQuery

按理说涉及“用开源代码提供网络服务是否算‘发布’”这一点，AGPL 应该是典型的“网络服务也是发布”的严格协议，但旧版竟然筛选不出来：

![image](https://user-images.githubusercontent.com/19969570/209159302-09ca7c31-be5c-4170-bbfc-eded095d13e9.png)

原始数据也说它没解决“隐私漏洞”：

![image](https://user-images.githubusercontent.com/19969570/209159988-42c20e24-f95e-4773-ab52-07f28b458644.png)

**Comment by TechQuery** [comment]
> > 隐私漏洞 Privacy Loophole 是指开发者对开源代码进行二次开发后， 需要对代码进行维护 ？ @TechQuery
> 
> 按理说涉及“用开源代码提供网络服务是否算‘发布’”这一点，AGPL 应该是典型的“网络服务也是发布”的严格协议，但旧版竟然筛选不出来：
> 
> ![image](https://user-images.githubusercontent.com/19969570/209159302-09ca7c31-be5c-4170-bbfc-eded095d13e9.png)
> 
> 原始数据也说它没解决“隐私漏洞”：
> 
> ![image](https://user-images.githubusercontent.com/19969570/209159988-42c20e24-f95e-4773-ab52-07f28b458644.png)

感觉不知哪次代码迁移时整错了，原版是对的，可能需要从原版校对数据了

![image](https://user-images.githubusercontent.com/19969570/209162160-0b32de20-4db0-4a8b-9186-3747784e3867.png)

**Comment by luojiyin1987** [comment]
![image](https://user-images.githubusercontent.com/6524977/209163035-86bffdc1-9308-4b65-af4d-3abaf5fd1c00.png)
原始数据里是要 解决隐私漏洞 问题的

**Comment by luojiyin1987** [comment]
![image](https://user-images.githubusercontent.com/6524977/209245438-76571770-b2db-4bf6-ae63-1a1566852f44.png)
看了自己实现的， 应该是原来某个函数实现问题的

**Comment by luojiyin1987** [comment]
> ![image](https://user-images.githubusercontent.com/6524977/209245438-76571770-b2db-4bf6-ae63-1a1566852f44.png) 看了自己实现的， 应该是原来某个函数实现问题的

单独拿   `genYesNo`  和 `awYesNo` 两个函数跑起来， 返回值是没问题的， xml 文件的原始数据也是没问题的。 
现在需要的是在本地跑起来 hexo ，加上log ，应该可以定位出问题。
@TechQuery

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/layout/license-tool.ejs#L279

我不知道  `site.data.license`  这个数据源从哪里来的 ， 通过打log ，发现没运行 `genYesNo` 和 `awYesNo` 两个函数 

@TechQuery

**Comment by TechQuery** [comment]
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b7d2c4acccb609704c5a12eba0bd4f0d87c8dec5/themes/Electron/layout/license-tool.ejs#L279
> 
> 我不知道  `site.data.license`  这个数据源从哪里来的 ， 通过打log ，发现没运行 `genYesNo` 和 `awYesNo` 两个函数 
> 
> @TechQuery 

https://github.com/kaiyuanshe/Wiki/blob/master/_data/license.yml

这个文件夹是 Hexo 专门用于注入数据的，我是把原始数据转成 YAML 存储的。

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/Wiki/pull/17    

@TechQuery   已经提pr了
