### ISSUE TITLE
补充新协议数据

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/Open-Source-License-filter#3]
## 数据来源

https://spdx.org/licenses/

## 收录标准

FSF Free/Libre 或 OSI Approved

**Comment by luojiyin1987** [comment]
[粗筛 符合FSF 或者 OSI 的协议](https://gist.github.com/luojiyin1987/15b55e4b1f42d188b9a908e9a96e2f5d)

**Comment by zhcxww** [comment]
增加了木兰许可在相关特征 #8
