### ISSUE TITLE
当 reuseCondition和infectionIntensity  都为 Negative 时 ，还该存在 infectionRange 的值？ 

### ISSUE THREAD

**Issue by luojiyin1987** [kaiyuanshe/Open-Source-License-filter#9]
在[文件 data.ts](https://github.dev/kaiyuanshe/Open-Source-License-filter/blob/master/source/data.ts) 中
```ts
{
        key: 'AFL-3.0',
        name: 'Academic Free License 3.0',
        link: 'https://opensource.org/licenses/AFL-3.0',
        feature: {
            popularity: FeatureAttitude.Negative,
            reuseCondition: FeatureAttitude.Negative,
            infectionIntensity: FeatureAttitude.Negative,
            infectionRange: InfectionRange.File,
         .....
        }
```
reuseCondition和infectionIntensity  都为 FeatureAttitude.Negative,时 , 即 没有重用性要求(reuseCondition) , 没有传染性(infectionIntensity ) ，  应该不会出现 传染范围，即 没有 infectionRange的值 ？

@TechQuery

**Comment by TechQuery** [comment]
这个协议的原始数据是怎样的？

**Comment by luojiyin1987** [comment]
[原始文件](https://github.com/luojiyin1987/license-tool/blob/main/components/matrix.json)

https://github.com/luojiyin1987/license-tool/blob/506829069c8977cf4bfd229f99c7e098e8ece27a/components/matrix.json#L19-L42
 有  mod  lib  file  都没做定义

**Comment by TechQuery** [comment]
https://github.com/kaiyuanshe/Open-Source-License-filter/blob/c87b668aadb0d6adac462079a2e4db4b6022749e/source/type.ts#L26

给这个字段打个问号，让它变成可选的，你看看算法会不会出什么问题。

**Comment by luojiyin1987** [comment]
还要做的
1. 更新 data.ts 文件中的 infectionRange 选项
2.  测试代码要改写

**Comment by luojiyin1987** [comment]
https://github.com/kaiyuanshe/Open-Source-License-filter/pull/10/commits/a28345af92a2eebcc3a212953b244caaaa2e3b9
测试代码代码感觉写的有点掩耳盗铃

**Comment by TechQuery** [comment]
> [a28345a](https://github.com/kaiyuanshe/Open-Source-License-filter/commit/a28345af92a2eebcc3a212953b244caaaa2e3b9) 测试代码代码感觉写的有点掩耳盗铃

我暂时想不出更严谨写法😂
